name: Build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout 5m
          working-directory: .

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test notify
        run: go test .
        working-directory: cmd/notify/

      - name: Build notify
        run: go build .
        working-directory: cmd/notify/

      - name: Test intercept
        run: go test .
        working-directory: cmd/intercept/

      - name: Build intercept
        run: go build .
        working-directory: cmd/intercept/